-- Story Pilot Privacy / Ghost Inbox
-- Server-only archive for Telegram Business message events.
-- The Mini App accesses this data only through the authenticated Vercel API and signed Edge gateway.

create table if not exists public.story_pilot_privacy_settings (
  telegram_user_id bigint primary key,
  anti_delete boolean not null default false,
  edit_history boolean not null default false,
  ghost_inbox boolean not null default false,
  retention_days integer not null default 30 check (retention_days between 1 and 3650),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.story_pilot_messages (
  telegram_user_id bigint not null,
  business_connection_id text not null,
  chat_id bigint not null,
  message_id bigint not null,
  direction text not null check (direction in ('incoming','outgoing')),
  sender_user_id bigint,
  sender_username text,
  sender_display_name text,
  chat_title text,
  text_content text,
  caption text,
  media_type text,
  media_file_id text,
  media_unique_id text,
  media_mime_type text,
  media_file_name text,
  media_file_size bigint,
  sent_at timestamptz not null,
  edited_at timestamptz,
  deleted_at timestamptz,
  content_hash text not null,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (telegram_user_id, chat_id, message_id)
);

create table if not exists public.story_pilot_message_versions (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null,
  chat_id bigint not null,
  message_id bigint not null,
  content_hash text not null,
  event_type text not null check (event_type in ('new','edit')),
  text_content text,
  caption text,
  media_type text,
  media_file_id text,
  media_unique_id text,
  observed_at timestamptz not null default now(),
  unique (telegram_user_id, chat_id, message_id, content_hash),
  foreign key (telegram_user_id, chat_id, message_id)
    references public.story_pilot_messages (telegram_user_id, chat_id, message_id)
    on delete cascade
);

create index if not exists story_pilot_messages_owner_sent_idx
  on public.story_pilot_messages (telegram_user_id, sent_at desc);
create index if not exists story_pilot_messages_owner_chat_sent_idx
  on public.story_pilot_messages (telegram_user_id, chat_id, sent_at desc);
create index if not exists story_pilot_messages_owner_deleted_idx
  on public.story_pilot_messages (telegram_user_id, deleted_at desc)
  where deleted_at is not null;
create index if not exists story_pilot_message_versions_lookup_idx
  on public.story_pilot_message_versions (telegram_user_id, chat_id, message_id, observed_at desc);

alter table public.story_pilot_privacy_settings enable row level security;
alter table public.story_pilot_messages enable row level security;
alter table public.story_pilot_message_versions enable row level security;

revoke all on table public.story_pilot_privacy_settings from anon, authenticated;
revoke all on table public.story_pilot_messages from anon, authenticated;
revoke all on table public.story_pilot_message_versions from anon, authenticated;
revoke all on sequence public.story_pilot_message_versions_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.story_pilot_privacy_settings to service_role;
grant select, insert, update, delete on table public.story_pilot_messages to service_role;
grant select, insert, update, delete on table public.story_pilot_message_versions to service_role;
grant usage, select on sequence public.story_pilot_message_versions_id_seq to service_role;
