-- Story Pilot Viewer Sync
-- Server-only tables. RLS is enabled with no client policies; the service role is used by Vercel functions.

create table if not exists public.story_pilot_viewer_sessions (
  telegram_user_id bigint primary key,
  session_ciphertext text not null,
  status text not null default 'active' check (status in ('active','reauth_required','disabled')),
  telegram_account_user_id bigint,
  telegram_account_username text,
  telegram_account_first_name text,
  last_poll_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.story_pilot_viewer_auth_challenges (
  telegram_user_id bigint primary key,
  challenge_ciphertext text not null,
  stage text not null check (stage in ('code','password')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists public.story_pilot_stories (
  telegram_user_id bigint not null,
  story_id integer not null,
  posted_at timestamptz not null default now(),
  expires_at timestamptz not null,
  watch_until timestamptz not null,
  audience text,
  protected boolean not null default false,
  active boolean not null default true,
  deleted_at timestamptz,
  last_views_count integer not null default 0,
  last_identified_count integer not null default 0,
  last_forwards_count integer not null default 0,
  last_reactions_count integer not null default 0,
  last_sync_at timestamptz,
  last_error text,
  primary key (telegram_user_id, story_id)
);

create table if not exists public.story_pilot_viewers (
  telegram_user_id bigint not null,
  story_id integer not null,
  viewer_user_id bigint not null,
  status text not null default 'provisional' check (status in ('provisional','confirmed')),
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  viewed_at timestamptz not null,
  confirmed_at timestamptz,
  username text,
  display_name text,
  is_contact boolean not null default false,
  reaction_json jsonb,
  notification_message_id bigint,
  primary key (telegram_user_id, story_id, viewer_user_id)
);

create table if not exists public.story_pilot_viewer_snapshots (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null,
  story_id integer not null,
  observed_at timestamptz not null default now(),
  total_views integer not null default 0,
  identified_views integer not null default 0,
  forwards_count integer not null default 0,
  reactions_count integer not null default 0
);

create index if not exists story_pilot_sessions_poll_idx
  on public.story_pilot_viewer_sessions (status, last_poll_at);

create index if not exists story_pilot_stories_watch_idx
  on public.story_pilot_stories (telegram_user_id, active, watch_until desc);

create index if not exists story_pilot_viewers_story_idx
  on public.story_pilot_viewers (telegram_user_id, story_id, status, viewed_at desc);

create index if not exists story_pilot_snapshots_story_idx
  on public.story_pilot_viewer_snapshots (telegram_user_id, story_id, observed_at desc);

alter table public.story_pilot_viewer_sessions enable row level security;
alter table public.story_pilot_viewer_auth_challenges enable row level security;
alter table public.story_pilot_stories enable row level security;
alter table public.story_pilot_viewers enable row level security;
alter table public.story_pilot_viewer_snapshots enable row level security;

revoke all on table public.story_pilot_viewer_sessions from anon, authenticated;
revoke all on table public.story_pilot_viewer_auth_challenges from anon, authenticated;
revoke all on table public.story_pilot_stories from anon, authenticated;
revoke all on table public.story_pilot_viewers from anon, authenticated;
revoke all on table public.story_pilot_viewer_snapshots from anon, authenticated;
